### ISSUE TITLE
ui-select2 validation tooltip 

### ISSUE THREAD

**Issue by poweredbyporkers** [refactorthis/xtform#7]
Hi,

When using ui-seelct2 the actual input against which you apply the xt-validate attribute becomes hidden due to this CSS

``` css
.select2-offscreen, .select2-offscreen:focus {
    clip: rect(0 0 0 0) !important;
    width: 1px !important;
    height: 1px !important;
    border: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
    overflow: hidden !important;
    position: absolute !important;
    outline: 0 !important;
    left: 0px !important;
    top: 0px !important;
}
```

therefore the validation tooltip ends up in the top left hand corner of the screen which isn't all that helpful :-)

So here you see that week commencing is requried but the tooltip is in the upper left hand corner

![image](https://cloud.githubusercontent.com/assets/3979789/2751597/8ab62460-c8dc-11e3-9366-b359acfb4df7.png)
